version: '3.8'
services:
  api-churn-prediction:
    build: ./api
    ports:
      - "7000:7000"
  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    ports:
      - "7880:7880"
