version: '3.8'
services:
  api-churn-prediction:
    build: ./api
    ports:
      - "7000:7000"
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
#  gradio:
#    build:
#      context: ./gradio
#      dockerfile: Dockerfile
#    ports:
#      - "7880:7880"
