---
apiVersion: apps/v1 # specifies the API version for the Deployment resource
kind: Deployment # defines the type of Kubernetes resource being created
metadata:
  name: ui-__PROJECT_NAME__ # the name of the deployment to identify this deployment resource
  labels:
    app: web # key-value pairs that can be used to organize and select resources
spec: # defines the desired state for the deployment
  replicas: 1 # сделала 1, чтобы уменьшить стоимость (в реальной работе нужно больше для отказоустойчивости, отсутствия downtime при обновлении и возможности поддерживать большее количество пользователей)
  selector:
    matchLabels:
      app: ui # criteria for selecting the pods that this deployment will manage (it selects pods with the label app: web)
  template: # describes the pods that will be created by the deployment
    metadata:
      labels:
        app: ui # labels assigned to the pods created by this deployment (must match the selector labels)
    spec: # defines the specification for the pod template
      containers: # lists the containers that will be running inside the pods
        - name: ui # the name of the container
          image: __VERSION_GRADIO__ # the Docker image used for this container
          ports:
            - containerPort: 7880 # specifies that port 80 should be exposed on the container
          env:
            - name: UI_URL
              value: "http://ui-service.default.svc.cluster.local"

---
apiVersion: v1 # specifies the API version for the Service resource
kind: Service
metadata:
  name: ui-__PROJECT_NAME__
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7880
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-__PROJECT_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: __VERSION_API__
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: api-__PROJECT_NAME__
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer

