channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - lz4==4.3.3
  - numpy==1.24.3
  - psutil==5.9.0
  - scikit-learn==1.3.1
  - scipy==1.11.4
name: mlflow-env
